name: Daily Update

on:
  schedule:
    - cron: '0 22 * * *' # 每天22点执行

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      - name: Run Python script
        run: python Guestbook/script/update.py 
